pypro/aperitivos/urls.py
from django.urls import path

from pypro.aperitivos.views import video, indice

app_name = 'aperitivos'
urlpatterns = [
    path('<slug:slug>', video, name='video'),
    path('', indice, name='indice'),
]

pypro/base/urls.py
from django.urls import path

from pypro.base.views import home

app_name = 'base'
urlpatterns = [
    path('', home, name='home'),
]

pypro/modulos/urls.py
from django.urls import path

from pypro.modulos import views

app_name = 'modulos'
urlpatterns = [
    path('<slug:slug>', views.detalhe, name='detalhe'),
    path('aulas/<slug:slug>', views.aula, name='aula'),
    path('', views.indice, name='indice')
]

pypro/turmas/urls.py
from django.urls import path

from pypro.turmas import views

app_name = 'turmas'
urlpatterns = [
    path('', views.indice, name='indice')
]

pypro/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

#  from pypro.base.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('contas/', include('django.contrib.auth.urls')),
    path('', include('pypro.base.urls')),
    path('aperitivos/', include('pypro.aperitivos.urls')),
    path('modulos/', include('pypro.modulos.urls')),
    path('turmas/', include('pypro.turmas.urls')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))

pypro/aperitivos/models.py
from django.db import models
from django.urls import reverse


class Video(models.Model):
    titulo = models.CharField(max_length=30)
    slug = models.SlugField(max_length=32)
    vimeo_id = models.CharField(max_length=30)
    creation = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse('aperitivos:video', args=(self.slug,))

    def __str__(self):
        return f'Video: {self.titulo}'

pypro/base/models.py
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.core.mail import send_mail
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """
        Creates and saves a User with the given email and password.
        """
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_staff', True)

        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')
        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    """
    App base User class.

    Email and password are required. Other fields are optional.
    """

    first_name = models.CharField(_('first name'), max_length=30, blank=True)
    email = models.EmailField(_('email address'), unique=True)
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        full_name = '%s' % (self.first_name)
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

pypro/modulos/models.py
from django.db import models
from django.urls import reverse
from ordered_model.models import OrderedModel


class Modulo(OrderedModel):
    titulo = models.CharField(max_length=46)
    publico = models.TextField()
    descricao = models.TextField()
    slug = models.SlugField(unique=True)

    class Meta(OrderedModel.Meta):
        pass

    def __str__(self):
        return self.titulo

    def get_absolute_url(self):
        return reverse('modulos:detalhe', kwargs={'slug': self.slug})


class Aula(OrderedModel):
    titulo = models.CharField(max_length=64)
    slug = models.SlugField(unique=True)
    modulo = models.ForeignKey('Modulo', on_delete=models.PROTECT)
    order_with_respect_to = 'modulo'
    vimeo_id = models.CharField(max_length=32)

    class Meta(OrderedModel.Meta):
        pass

    def __str__(self):
        return self.titulo

    def get_absolute_url(self):
        return reverse('modulos:aula', kwargs={'slug': self.slug})

pypro/turmas/models.py
from django.contrib.auth import get_user_model
from django.db import models


# Create your models here.

class Turma(models.Model):
    nome = models.CharField(max_length=64)
    slug = models.SlugField(max_length=64)
    inicio = models.DateField()
    fim = models.DateField()
    alunos = models.ManyToManyField(get_user_model(), through='Matricula')


class Matricula(models.Model):
    data = models.DateTimeField(auto_now_add=True)
    usuario = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    turma = models.ForeignKey(Turma, on_delete=models.CASCADE)

    class Meta:
        unique_together = [['usuario', 'turma']]
        ordering = ['turma', 'data']

pypro/aperitivos/views.py
# Create your views here.
from django.shortcuts import render, get_object_or_404

from pypro.aperitivos.models import Video


def indice(request):
    videos = Video.objects.order_by('creation').all()
    return render(request, 'aperitivos/indice.html', context={'videos': videos})


def video(request, slug):
    video = get_object_or_404(Video, slug=slug)
    return render(request, 'aperitivos/video.html', context={'video': video})

pypro/base/views.py
#  from django.http import HttpResponse


# Create your views here.
from django.shortcuts import render

from pypro.modulos import facade


def home(request):
    return render(request, 'base/home.html', {'MODULOS': facade.listar_modulos_ordenados()})

pypro/modulos/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

from pypro.modulos import facade


def detalhe(request, slug):
    modulo = facade.encontrar_modulo(slug)
    aulas = facade.listar_aulas_de_modulo_ordenados(modulo)
    return render(request, 'modulos/modulo_detalhe.html', {'modulo': modulo, 'aulas': aulas})


def indice(request):
    ctx = {'modulos': facade.listar_modulos_com_aulas()}
    return render(request, 'modulos/indice.html', ctx)


@login_required
def aula(request, slug):
    aula = facade.encontrar_aula(slug)
    return render(request, 'modulos/aula_detalhe.html', {'aula': aula})

pypro/turmas/views.py
from django.shortcuts import render


# Create your views here.
def indice(request):
    return render(request, 'turmas/indice.html')

pypro/aperitivos/templates/aperitivos/indice.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}Qwerty App - Videos{% endblock title %}
{% block description %}Site with all the videos{% endblock %}
{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1 class="mt-4 mb-4">Lista de Videos</h1>
                <ol>
                    {% for video in videos %}
                    <li><a href="{{ video.get_absolute_url }}" >{{ video.titulo | default:"Video No Disponible"}}</a></li>
                        {% empty %}
                        <li>No Hay video</li>
                    {% endfor %}
                </ol>
            </div>
        </div>
    </div>
{% endblock body %}

pypro/aperitivos/templates/aperitivos/video.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}Qwerty App - Video Aperitivo{% endblock title %}
{% block description %}Site with video for motivation{% endblock %}
{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1 class="mt-4 mb-4">{{ video.titulo | default:"Video No Disponible"}}</h1>
                <iframe src="https://player.vimeo.com/video/{{ video.vimeo_id }}" width="640" height="360" frameborder="0"
                        allow="autoplay; fullscreen" allowfullscreen></iframe>
            </div>
        </div>
    </div>
{% endblock body %}

pypro/base/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" type="text/css" href="../../static/css/style.css"/>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}Qwerty App{% endblock %}</title>

    <meta name="description" content="{% block description %}Site made in Django{% endblock %}">
    <meta name="author" content="Alfonso AG">

    <link rel="icon" href="{% static 'img/favicon.png' %}" type="image/png" sizes="16x16">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/scripts.js' %}"></script>

</head>
<body class="footer-fijo">
    <header class="container-fluid">
        <div class="row">
            <div class="col-md-12 pr-0 pl-0">
                <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                    <a class="navbar-brand" href="{% url 'base:home' %}">Qwerty</a>
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="navbar-nav ml-md-auto">
                            {% if user.is_authenticated %}
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="http://example.com"
                                       id="navbarDropdownMenuLink"
                                       data-toggle="dropdown">Módulos</a>
                                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                                        {% for modulo in MODULOS %}
                                            <a class="dropdown-item"
                                               href="{{ modulo.get_absolute_url }}">{{ modulo.titulo }}</a>
                                        {% endfor %}
                                       <!-- <div class="dropdown-divider"></div>
                                        <a class="dropdown-item" href="#">Separated link</a> -->
                                    </div>
                                </li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#"
                                       id="navbarDropdownMenuLink"
                                       data-toggle="dropdown">{{ user.first_name }}</a>
                                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                                        <div class="dropdown-item">
                                            <a class="btn btn-danger" href="{% url 'logout' %}"> Log Out</a>
                                        </div>
                                    </div>
                                </li>
                            {% else %}
                                <a type="button" class="btn btn-light my-2" href="{% url 'login' %}">Login</a>
                            {% endif %}

                        </ul>
                    </div>
                </nav>
            </div>
        </div>
    </header><!--end of header-->
    {% block body %}{% endblock body %}
    {% include 'base/footer.html' with contato_email='contacto@digimedios.com.co' %}
</body>
</html>

pypro/base/templates/base/footer.html
<footer class="main-footer mt-5 pt-4 text-light">
    <div class="container">
        <div class="row">
            <div class="col">
                <h3>Contact Us</h3>
                <address>
                    +55 31 994-721-117
                    <br/>
                    <a href="mailto:{{ contato_email }}" class="text-light">{{ contato_email }}</a>
                </address>
            </div>
        </div>
    </div>
    <div class="rights pb-4 pt-2">
        <div class="container">
            <div class="row">
                <div class="col">
                    {% now 'Y' %} Qwerty. All rights reserved.
                </div>
            </div>
        </div>
    </div>
</footer>

pypro/base/templates/base/home.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}Qwerty App - Home{% endblock title %}
{% block body %}
<main class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="carousel slide" id="carousel-414021">
                <ol class="carousel-indicators">
                    <li data-slide-to="0" data-target="#carousel-414021" class="active">
                    </li>
                    <li data-slide-to="1" data-target="#carousel-414021">
                    </li>
                    <li data-slide-to="2" data-target="#carousel-414021">
                    </li>
                </ol>
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <img class="d-block w-100" alt="Carousel Bootstrap First"
                             src="https://www.layoutit.com/img/sports-q-c-1600-500-1.jpg">
                        <div class="carousel-caption">
                            <h4>
                                First Thumbnail label
                            </h4>
                            <p>
                                Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta
                                gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.
                            </p>
                        </div>
                    </div>
                    <div class="carousel-item">
                        <img class="d-block w-100" alt="Carousel Bootstrap Second"
                             src="https://www.layoutit.com/img/sports-q-c-1600-500-2.jpg">
                        <div class="carousel-caption">
                            <h4>
                                Second Thumbnail label
                            </h4>
                            <p>
                                Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta
                                gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.
                            </p>
                        </div>
                    </div>
                    <div class="carousel-item">
                        <img class="d-block w-100" alt="Carousel Bootstrap Third"
                             src="https://www.layoutit.com/img/sports-q-c-1600-500-3.jpg">
                        <div class="carousel-caption">
                            <h4>
                                Third Thumbnail label
                            </h4>
                            <p>
                                Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta
                                gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.
                            </p>
                        </div>
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carousel-414021" data-slide="prev"><span
                        class="carousel-control-prev-icon"></span> <span class="sr-only">Previous</span></a> <a
                    class="carousel-control-next" href="#carousel-414021" data-slide="next"><span
                    class="carousel-control-next-icon"></span> <span class="sr-only">Next</span></a>
            </div>
        </div>
    </div>
</main>
<br>
<div class="container">
    <div class="row">
        <div class="col-md-12 pr-0 pl-0">
            <div class="row">
                <div class="col-md-4">
                    <div class="card">
                        <h5 class="card-header">
                            Margarita
                        </h5>
                        <div class="card-body">
                            <p class="card-text float-left mr-3">
                                <img src="{% static 'img/pizzeria1.png' %}" alt="">
                            <h6 class="text-justify">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ut
                                ante
                                non nibh placerat
                                feugiat nec id sem. Integer tellus velit, rutrum nec dictum ac, efficitur rhoncus
                                lectus. Etiam
                                ut arcu vitae mauris condimentum dignissim. Sed at tincidunt massa, eu tincidunt est.
                                Mauris
                                pretium elit id risus tempu</h6>
                            </p>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="card">
                        <h5 class="card-header">
                            Napolitana
                        </h5>
                        <div class="card-body">
                            <p class="card-text float-left mr-3">
                                <img src="{% static 'img/pizzeria3.png' %}" alt="">
                            <h6 class="text-justify">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ut
                                ante
                                non nibh placerat
                                feugiat nec id sem. Integer tellus velit, rutrum nec dictum ac, efficitur rhoncus
                                lectus. Etiam
                                ut arcu vitae mauris condimentum dignissim. Sed at tincidunt massa, eu tincidunt est.
                                Mauris
                                pretium elit id risus tempu</h6>
                            </p>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="card">
                        <h5 class="card-header">
                            Potatoes
                        </h5>
                        <div class="card-body">
                            <p class="card-text float-left mr-3 ">
                                <img src="{% static 'img/potatoes.png' %}" alt="">
                            <h6 class="text-justify">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ut
                                ante
                                non nibh placerat
                                feugiat nec id sem. Integer tellus velit, rutrum nec dictum ac, efficitur rhoncus
                                lectus. Etiam
                                ut arcu vitae mauris condimentum dignissim. Sed at tincidunt massa, eu tincidunt est.
                                Mauris
                                pretium elit id risus tempu</h6>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<br>
<main class="container">
    <div class="row">
        <div class="col-md-3">
        </div>
        <div class="col-md-6">
            <h3>Contact Us</h3>
            <form action="https://digimedios.us10.list-manage.com/subscribe/post?u=0b2192a85923702ed2245b66e&amp;id=ea9ef63ccc"
                  method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form"
                  class="form-row align-items-center"
                  target="_blank" novalidate>
                <div class="form-row align-items-center">
                    <div class="col-auto">
                        <label for="mce-EMAIL"> Email address </label>
                        <input type="email" value="" name="EMAIL" class="form-control required" id="mce-EMAIL"
                               placeholder="example@email.com">
                    </div>
                    <div class="col-auto">
                        <label for="mce-FNAME"> Name </label>
                        <input type="text" value="" name="FNAME" class="form-control" id="mce-FNAME"
                               placeholder="Your Name">
                    </div>
                    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
                    <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text"
                                                                                              name="b_0b2192a85923702ed2245b66e_ea9ef63ccc"
                                                                                              tabindex="-1" value="">
                    </div>
                    <div class="col-auto mt-4">
                        <input type="submit" value="Subscribe" name="subscribe"
                               id="mc-embedded-subscribe" class="btn btn-primary"></div>
                </div>
            </form>
        </div>
        <div class="col-md-3">
        </div>
    </div>
</main>
{% endblock body %}

pypro/modulos/templates/modulos/aula_detalhe.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}{{ aula.titulo }}{% endblock title %}
{% block description %}Site with video for motivation{% endblock %}
{% block body %}
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="#">Home</a></li>
        <li class="breadcrumb-item"><a href="{{aula.modulo.get_absolute_url}}">{{aula.modulo.titulo}}</a></li>
        <li class="breadcrumb-item active" aria-current="page">{{aula.titulo}}</li>
      </ol>
    </nav>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1 class="mt-4 mb-4">{{ aula.titulo }}</h1>
                <iframe src="https://player.vimeo.com/video/{{ aula.vimeo_id }}" width="640" height="360" frameborder="0"
                        allow="autoplay; fullscreen" allowfullscreen></iframe>
            </div>
        </div>
    </div>
{% endblock body %}

pypro/modulos/templates/modulos/indice.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}Qwerty App - {{ modulo.titulo}}{% endblock title %}
{% block description %}Página com detalhes do módulo {{ modulo.titulo }}{% endblock %}
{% block body %}
    <div class="container">
    {% for modulo in modulos %}
        <div class="row">
            <div class="col-md-12">
                <h1 class="mt-4 mb-4">{{ modulo.titulo }}</h1>
                <dl>
                    <dt>Público</dt>
                    <dd>{{ modulo.publico }}</dd>
                </dl>
                <dl>
                    <dt>Descrição</dt>
                    <dd>{{ modulo.descricao }}</dd>
                </dl>
                <h2>Aulas</h2>
                <ol>
                    {% for aula in modulo.aulas %}
                        <li> <a href="{{ aula.get_absolute_url }}" >{{ aula.titulo }}</a></li>
                    {% endfor %}
                </ol>

            </div>
        </div>
    {% endfor %}
    </div>
{% endblock body %}

pypro/modulos/templates/modulos/modulo_detalhe.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}Qwerty App - {{ modulo.titulo}}{% endblock title %}
{% block description %}Página com detalhes do módulo {{ modulo.titulo }}{% endblock %}
{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1 class="mt-4 mb-4">{{ modulo.titulo }}</h1>
                <dl>
                    <dt>Público</dt>
                    <dd>{{ modulo.publico }}</dd>
                </dl>
                <dl>
                    <dt>Descrição</dt>
                    <dd>{{ modulo.descricao }}</dd>
                </dl>
                <h2>Aulas</h2>
                <ol>
                    {% for aula in aulas %}
                        <li> <a href="{{ aula.get_absolute_url }}" >{{ aula.titulo }}</a></li>
                    {% endfor %}
                </ol>

            </div>
        </div>
    </div>
{% endblock body %}

pypro/turmas/templates/turmas/indice.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}Índice de Turmas{% endblock title %}
{% block description %}Página com todas turmas do curso{% endblock %}
{% block body %}
    <div class="container">
    {% for modulo in modulos %}
        <div class="row">
            <div class="col-md-12">
                <h1 class="mt-4 mb-4">{{ modulo.titulo }}</h1>
                <dl>
                    <dt>Público</dt>
                    <dd>{{ modulo.publico }}</dd>
                </dl>
                <dl>
                    <dt>Descrição</dt>
                    <dd>{{ modulo.descricao }}</dd>
                </dl>
                <h2>Aulas</h2>
                <ol>
                    {% for aula in modulo.aulas %}
                        <li> <a href="{{ aula.get_absolute_url }}" >{{ aula.titulo }}</a></li>
                    {% endfor %}
                </ol>

            </div>
        </div>
    {% endfor %}
    </div>
{% endblock body %}